trigger:
  paths:
    include:
    - infrastructure/*

pool:
  vmImage: 'windows-2022'

jobs:
- job: TestEcho
  displayName: 'Echo Change'
  steps:
  - script: echo "There has been a change in infra folder"
    displayName: 'Echo Change'
